version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: social_platform_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_platform
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - social_platform_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Add pgAdmin for database management (optional)
  pgadmin:
    image: dpage/pgadmin4
    container_name: social_platform_pgadmin
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - social_platform_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  social_platform_network:
    driver: bridge 